version: "3"

services:
  profile_postgres:
    container_name: Profile_Postgres
    image: postgres:14.5
    env_file: .env
    ports:
      - 5555:5432
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d Profile" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - .\\volumes\\postgres-data\\:/var/lib/postgresql/data

  profile_migrator:
    container_name: Profile_Migrator
    build:
      context: ./../
      dockerfile: ./migrator/ProfilerService.Migrator/Dockerfile
    env_file: .env
    healthcheck:
            test: [ "CMD-SHELL", "echo", "1" ]
            interval: 1s
            timeout: 1s
            retries: 5
    depends_on:
      profile_postgres:
        condition: service_healthy

  profile_grpc:
    container_name: Profile_GRPC
    build:
      context: ./../
      dockerfile: ./src/ProfilerService.Grpc/Dockerfile
    env_file: .env
    ports:
      - 5064:80
    depends_on:
      profile_migrator:
        condition: service_completed_successfully
      profile_postgres:
        condition: service_healthy